/**
 * about — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /aboutus.php, /mission.php, /visionmission.php, /schoolmoto.php, /schoolsong.php
 */
export interface AboutContent {
  about: string;
  mission: string;
  vision: string;
  moto: string;
  song: string;
}

export const about: AboutContent = {
  about: `Welcome to Krishna Public School,We believe that when inspirational young student work with inspired teachers, mentors, and curricula, there are no limits to what can be achieved Krishna Public School is a progressive senior secondary school that educates students of exceptional promise for a lifetime of leadership and contribution to society.At Krishna, the learning experience includes faculty advisers, mentors, independent study opportunities, small class sizes, a diverse group of talented students, and a curriculum of extraordinary depth KPS aims to equip students fully with the skills and knowledge to attend the worlds finest universities, serve as successful leaders in their communities and effect positive change in the world.`,
  mission: `1. After the long discussion with the students, teachers and parents of the school, it is identified that the issue of effective communication among student and teachers is to be enhanced to have a fearless atmosphere for the overall development of the child. 2. Whereas the teachers of the school felt that better learning resources are to be provided in the class rooms for the students and the school will improve school attendance and performance of the students in all the spheres. 3. Further in respect and regard with the community, the school will try to achieve plantation of tress in nearby areas and will be bring awareness in people about proving first aid. 4. Thinking a mission towards community the earnest need of the hour is to make the society aware about the conservation of�water. It is only possible by harvesting water through different resources like rainwater harvesting, rooftop rainwater harvesting.`,
  vision: `Krishna Public School Aims at leading the present generation towards modernity while retaining moral and ethical values of our traditional glorious Indian culture. So the main concern of the school is at developing the total personality of the child to make him / her a better citizen of tomorrow by instilling in him / her the quality of leadership, co-operation and team work and tolerance regards for elders and respect for the noble ideas and norms of society and reverence for Indian culture.`,
  moto: `The Logo has been carefully designed to reflect the philosophy of the School. It depicts a true and fair open book and rising sun. The openness denotes openness of thoughts and deeds i.e. transparency of our activities. The book symbolises, acquisition of knowledge and learning. The Motto of the School: Labor Omnia Vincit means success all conquers.`,
  song: `The school is affiliated to the Central Board of Secondary Education, New Delhi and purposes students from standard Ist to XIIth strictly in accordance with the syllabi prescribed by the Board. Subjects Offered: The medium of instruction is English and Subjects are English, Hindi, Maths, Social Science, Science, Arts, Physical Education, Computers, Sanskrit, Drawing. Senior Secondary Classes (XI & XII): Compulsory subject English Core Science Stream Physics, Chemistry, Biology, Maths, Computer Science/ Physical Education/ Fine Arts. Commerce Stream Accountancy, Business Studies, Economics ,Maths, Computer Science/ Physical Education/ Fine Arts.`,
};
