/**
 * contact — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /contactus.php
 */
export interface ContactInfo {
  address: string;
  phones: string[];
  emails: string[];
  socials: { platform: string; url: string }[];
}

export const contact: ContactInfo = {
  address: `NH-58, By Pass, Shradha Puri, Kanker Khera ,Meerut`,
  phones: ["0121-2554335","9219684588"],
  emails: ["krishna.pub.sch@gmail.com"],
  socials: [], // TBD — legacy site had no live social links
};
