/**
 * downloads — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /downloads.php
 */
export interface DownloadItem {
  title: string;
  url: string;
}

export const downloads: DownloadItem[] = [
  {
    "title": "MANDATORY PUBLIC DISCLOSURE",
    "url": "https://www.krishnapublicschoolmeerut.in/Downloads/71MANDATORY PUBLIC DISCLOSURE.pdf"
  },
  {
    "title": "CALEN.",
    "url": "https://www.krishnapublicschoolmeerut.in/Downloads/6360192 CALEN..pdf"
  },
  {
    "title": "KPS_prospectus_draft4",
    "url": "https://www.krishnapublicschoolmeerut.in/Downloads/4KPS_prospectus_draft4.pdf"
  },
  {
    "title": "ADMISSION OPEN.docx",
    "url": "https://www.krishnapublicschoolmeerut.in/Downloads/11ADMISSION OPEN.docx"
  }
];
