/**
 * facilities — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /infrastructure.php?InfraId=1..13
 */
export interface Facility {
  id: number;
  slug: string;
  name: string;
  description: string;
  images: string[];
}

export const facilities: Facility[] = [
  {
    "id": 1,
    "slug": "library",
    "name": "Library",
    "description": "The Library Our endeavour is to inculcate the habit of reading in the growing children so that they learn to go beyond the curriculum. Krishna has a well established library which is an integral part of the school. It is managed by a well qual",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/1lib.png"
    ]
  },
  {
    "id": 2,
    "slug": "labs",
    "name": "Labs",
    "description": "Laboratories In the country like India where Mr. Abdul kalam spent maximum time of his life in science laboratories only and earned world wide position for the country in Science and Technology. Our budding scientists have to be given properly mainta",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/2LABS.png"
    ]
  },
  {
    "id": 3,
    "slug": "dance-room",
    "name": "Dance Room",
    "description": "ACTIVITY ZONE We at KPS believe that each individual has a responsibility towards the family, society, nation and the environment. To inculcate and enhance these qualities among the students, the school organizes various activities at activity",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/3DANCE ROOM.jpg"
    ]
  },
  {
    "id": 4,
    "slug": "music-room",
    "name": "Music Room",
    "description": "Music Room",
    "images": []
  },
  {
    "id": 5,
    "slug": "activity-room",
    "name": "Activity Room",
    "description": "ACTIVITY ZONE We at KPS believe that each individual has a responsibility towards the family, society, nation and the environment. To inculcate and enhance these qualities among the students, the school organizes various activities at activity",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/5ACTIVITY ROOM.jpg"
    ]
  },
  {
    "id": 6,
    "slug": "canteen",
    "name": "Canteen",
    "description": "School Canteen",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/6SCHOOL CANTEEN 2.jpg"
    ]
  },
  {
    "id": 9,
    "slug": "art-room",
    "name": "Art Room",
    "description": "Fine Art Room",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/9fine art 2.jpg"
    ]
  },
  {
    "id": 12,
    "slug": "swimming-pool",
    "name": "Swimming Pool",
    "description": "Swimming Pool",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/12SWIMMING 12.jpg"
    ]
  },
  {
    "id": 13,
    "slug": "playground",
    "name": "PlayGround",
    "description": "Co-curricular Activities: Activities play an important role in developing the personality of the students apart from scholastic achievements. The curriculum consists of a multitude of activities.",
    "images": [
      "https://www.krishnapublicschoolmeerut.in/InfraImages/13SPORTS DAY1  P.T..jpg"
    ]
  }
];
