/**
 * gallery — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /photogallery.php, /gallery.php?GalleryCatId=1..15
 */
export interface GalleryImage {
  url: string;
  caption: string | null;
}

export interface GalleryCategory {
  categoryId: number;
  slug: string;
  name: string;
  images: GalleryImage[];
}

export const gallery: GalleryCategory[] = [
  {
    "categoryId": 1,
    "slug": "image-gallery",
    "name": "IMAGE GALLERY",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/162WhatsApp Image 2024-05-21 at 11.32.33 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/163WhatsApp Image 2024-05-21 at 11.32.40 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/164WhatsApp Image 2024-05-21 at 11.32.38 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/168WhatsApp Image 2024-05-21 at 11.46.31 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/169WhatsApp Image 2024-05-21 at 11.44.49 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/170WhatsApp Image 2024-05-21 at 11.42.58 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/171WhatsApp Image 2024-05-21 at 11.42.43 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/172WhatsApp Image 2024-05-21 at 11.42.43 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/173WhatsApp Image 2024-05-21 at 11.42.42 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/105WhatsApp Image 2023-06-05 at 5.33.10 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/104ENVIRONMENT DAY1.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/2flower `1.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5IMG-20150207-WA0006.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/4IMG-20150207-WA0001.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/6A 1.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/7A3.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/8DSC06987.JPG",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/9A5.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/158WhatsApp Image 2024-05-18 at 1.39.56 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/159WhatsApp Image 2024-05-18 at 1.39.59 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/160WhatsApp Image 2024-05-18 at 2.36.44 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/102WhatsApp Image 2023-06-06 at 8.59.33 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/103WhatsApp Image 2023-06-06 at 8.59.32 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/114WhatsApp Image 2023-06-21 at 10.12.59 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/161WhatsApp Image 2024-05-21 at 11.32.38 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/112WhatsApp Image 2023-06-21 at 10.13.35 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/113WhatsApp Image 2023-06-21 at 9.44.51 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/115WhatsApp Image 2023-06-21 at 10.13.31 AM.jpeg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 2,
    "slug": "function",
    "name": "FUNCTION",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/30DSC_9260.JPG",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/125WhatsApp Image 2024-04-28 at 9.36.52 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/126WhatsApp Image 2024-04-22 at 5.18.57 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/98WhatsApp Image 2023-04-15 at 8.44.17 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/10WhatsApp Image 2023-04-01 at 12.24.53 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/34IMG-20191007-WA0064.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/35WhatsApp Image 2023-04-01 at 12.24.52 PM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/36LIBRARY PHOTO.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/37LIBRARY PHOTO.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/38IMG-20190129-WA0018.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/39WhatsApp Image 2023-04-01 at 12.24.51 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/42WhatsApp Image 2023-02-22 at 2.45.46 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/412.png",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/43WhatsApp Image 2023-03-26 at 9.09.47 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/44WhatsApp Image 2023-03-26 at 9.09.47 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/45WhatsApp Image 2023-04-01 at 3.37.04 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/25WhatsApp Image 2023-04-01 at 12.24.50 PM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/26IMG-20191007-WA0071.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/46WhatsApp Image 2023-04-01 at 12.24.50 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/111WhatsApp Image 2023-04-15 at 8.43.53 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/47WhatsApp Image 2023-04-01 at 12.24.50 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/48WhatsApp Image 2023-04-01 at 12.24.55 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/118WhatsApp Image 2023-11-10 at 2.23.46 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/99WhatsApp Image 2023-04-15 at 8.40.42 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/101Screenshot 2023-04-05 112430.png",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/100WhatsApp Image 2023-04-15 at 8.40.41 PM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/119WhatsApp Image 2023-11-04 at 2.49.38 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/117DSC_9308.JPG",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/120WhatsApp Image 2023-11-14 at 7.57.26 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/121DSC_9297.JPG",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/27IMG-20190928-WA0079.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/28WhatsApp Image 2023-04-01 at 10.10.54 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/29WhatsApp Image 2023-04-01 at 10.10.55 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/31IMG-20190129-WA0029.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/32IMG-20190926-WA0059.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/33bio.JPG",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/97WhatsApp Image 2023-04-15 at 8.43.54 PM (1).jpeg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 3,
    "slug": "pariksha-pe-charcha",
    "name": "pariksha pe charcha",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/11WhatsApp Image 2023-01-27 at 1.50.44 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/49WhatsApp Image 2023-01-27 at 11.42.29 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/50WhatsApp Image 2023-01-27 at 11.42.28 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/51WhatsApp Image 2023-01-27 at 1.47.42 PM.jpeg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 4,
    "slug": "toppers-2019-20",
    "name": "TOPPERS 2019 - 20",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5302.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/64Screenshot 2023-04-05 113854.png",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5201.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/6105.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/62Graphic1.JPG",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/63Screenshot 2023-04-05 112446.png",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5403.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5504.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5608.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5712.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5801.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/5902.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/6003.jpg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 5,
    "slug": "toppers-2020-2021",
    "name": "TOPPERS 2020-2021",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/65ABOVE 85 TOPPERS STUD..jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/7692.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/7791.2.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/7891.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/7994%.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/8094%.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/661 AAYUSH SHARMA.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/671 ARHAAN AHMAD.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/692 ADITYA LOHKNA.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/704 TANUSHREE.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/725 GAURI SHARMA.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/736 ANSHU TOMAR.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/7426 TOPERS ABOVE 80.JPG",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/7593.4%.jpg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 6,
    "slug": "toppers-2021-2022",
    "name": "TOPPERS 2021-2022",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/24RESULT 2017-2018.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/89X.... TOPERS ABOVE.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/901.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/915.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/929.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/932.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/943.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/954.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/81IST XII TOPERS ABOVE.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/82IIND XII. TOPERS ABOVE.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/831.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/842.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/854.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/865.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/876.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/888.jpg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 7,
    "slug": "archive-gallery-7",
    "name": "Archive Gallery 7",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/23RESULT 2018-2019.jpg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 9,
    "slug": "result-2022-23",
    "name": "RESULT - 2022 - 23",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/110WhatsApp Image 2023-05-30 at 8.34.32 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/96CLASS X.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/109XII TOPERS ABOVE.jpg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 10,
    "slug": "archive-gallery-10",
    "name": "Archive Gallery 10",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/106WhatsApp Image 2023-05-30 at 8.34.32 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/108CLASS X.jpg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/107XII TOPERS ABOVE.jpg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 11,
    "slug": "krishna-news",
    "name": "KRISHNA NEWS",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/165WhatsApp Image 2024-05-21 at 11.42.44 AM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/166WhatsApp Image 2024-05-21 at 11.42.44 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/167WhatsApp Image 2024-05-21 at 11.42.44 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/122WhatsApp Image 2023-10-24 at 9.07.35 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/123WhatsApp Image 2023-10-25 at 1.14.24 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/124WhatsApp Image 2023-10-25 at 8.24.01 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/116WhatsApp Image 2023-06-22 at 11.12.14 AM.jpeg",
        "caption": null
      }
    ]
  },
  {
    "categoryId": 12,
    "slug": "result-2023-24",
    "name": "RESULT 2023-24",
    "images": [
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/127BOTH SIDE.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/128WhatsApp Image 2024-05-13 at 3.16.42 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/129WhatsApp Image 2024-05-13 at 3.16.43 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/130WhatsApp Image 2024-05-20 at 8.40.18 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/131WhatsApp Image 2024-05-20 at 8.40.19 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/132WhatsApp Image 2024-05-18 at 2.33.03 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/133WhatsApp Image 2024-05-18 at 2.33.03 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/134WhatsApp Image 2024-05-16 at 6.56.19 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/135WhatsApp Image 2024-05-16 at 6.56.19 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/136WhatsApp Image 2024-05-16 at 6.56.20 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/137WhatsApp Image 2024-05-16 at 6.56.20 PM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/138WhatsApp Image 2024-05-16 at 6.56.20 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/139WhatsApp Image 2024-05-16 at 6.56.21 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/140WhatsApp Image 2024-05-16 at 6.56.21 PM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/141WhatsApp Image 2024-05-16 at 6.56.21 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/142WhatsApp Image 2024-05-16 at 6.56.22 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/143WhatsApp Image 2024-05-16 at 6.56.22 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/144WhatsApp Image 2024-05-16 at 6.56.23 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/145WhatsApp Image 2024-05-16 at 6.56.23 PM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/146WhatsApp Image 2024-05-16 at 6.56.23 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/147WhatsApp Image 2024-05-16 at 6.56.24 PM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/148WhatsApp Image 2024-05-16 at 6.56.24 PM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/149WhatsApp Image 2024-05-14 at 12.51.55 PM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/150WhatsApp Image 2024-05-16 at 9.02.35 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/151WhatsApp Image 2024-05-16 at 9.05.07 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/152WhatsApp Image 2024-05-16 at 9.05.07 AM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/153WhatsApp Image 2024-05-16 at 9.05.07 AM (3).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/154WhatsApp Image 2024-05-16 at 9.05.07 AM.jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/155WhatsApp Image 2024-05-16 at 9.05.08 AM (1).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/156WhatsApp Image 2024-05-16 at 9.05.08 AM (2).jpeg",
        "caption": null
      },
      {
        "url": "https://www.krishnapublicschoolmeerut.in/IGTImages/157WhatsApp Image 2024-05-14 at 9.08.22 AM.jpeg",
        "caption": null
      }
    ]
  }
];
