/**
 * homework — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /hwclass.php, /homeworklist.php?DCatId=1..15
 */
export interface HomeworkItem {
  title: string;
  url: string;
}

export interface HomeworkClass {
  classId: number;
  className: string;
  items: HomeworkItem[];
}

export const homework: HomeworkClass[] = [
  {
    "classId": 1,
    "className": "CLASS IST",
    "items": [
      {
        "title": "CL 1 MATH CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/9CL 1 MATH CH 2.pdf"
      },
      {
        "title": "CL 1 MATH CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/8CL 1 MATH CH 1.pdf"
      },
      {
        "title": "CL 1 HIN CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/7CL 1 HIN CH 2.pdf"
      },
      {
        "title": "CL 1 HIN CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/6CL 1 HIN CH 1.pdf"
      },
      {
        "title": "CL 1 EVS CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/5CL 1 EVS CH 2.pdf"
      },
      {
        "title": "CL 1 EVS CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/4CL 1 EVS CH 1.pdf"
      },
      {
        "title": "cl 1 eng ch 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/3cl 1 eng ch 2.pdf"
      },
      {
        "title": "cl 1 eng ch 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/2cl 1 eng ch 1.pdf"
      },
      {
        "title": "ST",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/11ST.pdf"
      }
    ]
  },
  {
    "classId": 2,
    "className": "CLASS IIND",
    "items": [
      {
        "title": "Writing 02",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/28Writing_02.pdf"
      },
      {
        "title": "class 2 Eng worksheet ch 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/27class 2 Eng worksheet ch 1.pdf"
      },
      {
        "title": "class 2 eng ch 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/26class 2 eng ch 2.pdf"
      },
      {
        "title": "cl 2 math ch 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/25cl 2 math ch 2.pdf"
      },
      {
        "title": "cl 2 math ch 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/24cl 2 math ch 1.pdf"
      },
      {
        "title": "cl 2 hindi ch 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/23cl 2 hindi ch 1.pdf"
      },
      {
        "title": "cl 2 hin ch 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/22cl 2 hin ch 2.pdf"
      },
      {
        "title": "cl 2 evs ch 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/21cl 2 evs ch 2.pdf"
      },
      {
        "title": "cl 2 evs ch 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/20cl 2 evs ch 1.pdf"
      }
    ]
  },
  {
    "classId": 3,
    "className": "CLASS IIIRD",
    "items": [
      {
        "title": "CL 4 MATH CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/44CL 4 MATH CH 1.pdf"
      },
      {
        "title": "Writing 3",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/37Writing 3.pdf"
      },
      {
        "title": "CL 3 MATH CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/36CL 3 MATH CH 2.pdf"
      },
      {
        "title": "CL 3 MATH CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/35CL 3 MATH CH 1.pdf"
      },
      {
        "title": "CL 3 HINDI CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/34CL 3 HINDI CH 1.pdf"
      },
      {
        "title": "CL 3 HIN CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/33CL 3 HIN CH 2.pdf"
      },
      {
        "title": "CL 3 EVS CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/32CL 3 EVS CH 2.pdf"
      },
      {
        "title": "CL 3 EVS CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/31CL 3 EVS CH 1.pdf"
      },
      {
        "title": "CL 3 ENG CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/30CL 3 ENG CH 2.pdf"
      },
      {
        "title": "CL 3 ENG CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/29CL 3 ENG CH 1.pdf"
      }
    ]
  },
  {
    "classId": 4,
    "className": "CLASS IVTH",
    "items": [
      {
        "title": "Writing-04",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/54Writing-04.pdf"
      },
      {
        "title": "math",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/53math.pdf"
      },
      {
        "title": "CL 4 MATH CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/52CL 4 MATH CH 2.pdf"
      },
      {
        "title": "CL 4 MATH CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/51CL 4 MATH CH 1.pdf"
      },
      {
        "title": "CL 4 HIN CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/50CL 4 HIN CH 2.pdf"
      },
      {
        "title": "CL 4 HIN CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/49CL 4 HIN CH 1.pdf"
      },
      {
        "title": "CL 4 EVS CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/48CL 4 EVS CH 2.pdf"
      },
      {
        "title": "CL 4 EVS CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/47CL 4 EVS CH 1.pdf"
      },
      {
        "title": "CL 4 ENG CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/46CL 4 ENG CH 2.pdf"
      },
      {
        "title": "CL 4 ENG CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/45CL 4 ENG CH 1.pdf"
      }
    ]
  },
  {
    "classId": 5,
    "className": "CLASS VTH",
    "items": [
      {
        "title": "Writing-05-new",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/63Writing-05-new.pdf"
      },
      {
        "title": "math",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/62math.pdf"
      },
      {
        "title": "CL 5 MATH CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/61CL 5 MATH CH 2.pdf"
      },
      {
        "title": "CL 5 HIN CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/60CL 5 HIN CH 2.pdf"
      },
      {
        "title": "CL 5 HIN CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/59CL 5 HIN CH 1.pdf"
      },
      {
        "title": "CL 5 EVS CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/58CL 5 EVS CH 2.pdf"
      },
      {
        "title": "CL 5 EVS CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/57CL 5 EVS CH 1.pdf"
      },
      {
        "title": "CL 5 ENG CH 2",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/56CL 5 ENG CH 2.pdf"
      },
      {
        "title": "CL 5 ENG CH 1",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/55CL 5 ENG CH 1.pdf"
      }
    ]
  },
  {
    "classId": 6,
    "className": "CLASS VITH",
    "items": [
      {
        "title": "CLASS 6 SCIENCE",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/65CLASS 6 SCIENCE.pdf"
      },
      {
        "title": "CLASS 6 MATHS",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/64CLASS 6 MATHS.pdf"
      }
    ]
  },
  {
    "classId": 7,
    "className": "CLASS VIITH",
    "items": [
      {
        "title": "CLASS 7 SCIENCE",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/67CLASS 7 SCIENCE.pdf"
      },
      {
        "title": "CLASS 7 MATHS",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/66CLASS 7 MATHS.pdf"
      }
    ]
  },
  {
    "classId": 8,
    "className": "CLASS VIIITH",
    "items": [
      {
        "title": "CLASS 8 SCIENCE",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/69CLASS 8 SCIENCE.pdf"
      },
      {
        "title": "CLASS 8 MATHS",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/68CLASS 8 MATHS.pdf"
      }
    ]
  },
  {
    "classId": 9,
    "className": "CLASS IXTH",
    "items": [
      {
        "title": "class 9 Math Ch 1 Number system book",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/81class 9 Math Ch 1 Number system book.pdf"
      },
      {
        "title": "class 9 math ch 1 number suystem ncert sol",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/80class 9 math ch 1 number suystem ncert sol.pdf"
      },
      {
        "title": "cl9 sst ch1 democracy book",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/79cl9 sst ch1 democracy book.pdf"
      },
      {
        "title": "cl9 sci ch1 matter around us add.qus",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/78cl9 sci ch1 matter around us add.qus.pdf"
      },
      {
        "title": "CL9 Sci ch1 matter ard us solution",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/77CL9 Sci ch1 matter ard us solution.pdf"
      },
      {
        "title": "cl 9 sst hin ch 1 democracy",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/76cl 9 sst hin ch 1 democracy.pdf"
      },
      {
        "title": "Cl 9 sci hindi ch1 matter around us",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/75Cl 9 sci hindi ch1 matter around us.pdf"
      },
      {
        "title": "CL 9 SCI CH 1 MATTER AROUND US",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/74CL 9 SCI CH 1 MATTER AROUND US.pdf"
      },
      {
        "title": "SST IX",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/73SST IX.pdf"
      },
      {
        "title": "science IX",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/72science IX.pdf"
      },
      {
        "title": "IX MATHS",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/71IX MATHS.pdf"
      },
      {
        "title": "Food Production IX (409) (1)",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/70Food Production IX (409) (1).pdf"
      }
    ]
  },
  {
    "classId": 10,
    "className": "CLASS XTH",
    "items": [
      {
        "title": "Food Production X (409)",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/92Food Production X (409).pdf"
      },
      {
        "title": "CL 10 SST CH 1 Rise of nationalism book",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/91CL 10 SST CH 1 Rise of nationalism book.pdf"
      },
      {
        "title": "CL 10 SST CH 1 HINDI  RISE OF NATIONALISM",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/90CL 10 SST CH 1 HINDI  RISE OF NATIONALISM.pdf"
      },
      {
        "title": "cl 10 sci ch 1 chem. reac. n equ. add qus",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/89cl 10 sci ch 1 chem. reac. n equ. add qus.pdf"
      },
      {
        "title": "Cl 10 Sci Ch 1 chem. eq n react. book",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/88Cl 10 Sci Ch 1 chem. eq n react. book.pdf"
      },
      {
        "title": "cl 10 math ch1 real number add qus",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/87cl 10 math ch1 real number add qus.pdf"
      },
      {
        "title": "cl 10 math ch1 real num solution",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/86cl 10 math ch1 real num solution.pdf"
      },
      {
        "title": "cl 10 math ch 1 real number book",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/85cl 10 math ch 1 real number book.pdf"
      },
      {
        "title": "CLASS X SST",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/84CLASS X SST.pdf"
      },
      {
        "title": "CLASS X SCIENCE",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/83CLASS X SCIENCE.pdf"
      },
      {
        "title": "CLASS X MATHS FINAL",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/82CLASS X MATHS FINAL.pdf"
      }
    ]
  },
  {
    "classId": 11,
    "className": "CLASS XITH",
    "items": []
  },
  {
    "classId": 12,
    "className": "CLASS XII",
    "items": [
      {
        "title": "CLASS XII BST FINAL",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/99CLASS XII BST FINAL.pdf"
      },
      {
        "title": "Class 12 physics",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/98Class 12 physics.pdf"
      },
      {
        "title": "ACCOUNTS XII 2020 WM FINAL",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/97ACCOUNTS XII 2020 WM FINAL.pdf"
      },
      {
        "title": "Accountancy Sr.Sec 2020-21",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/96Accountancy_Sr.Sec_2020-21.pdf"
      },
      {
        "title": "Class Maths",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/9512 Class Maths.pdf"
      },
      {
        "title": "Class chemistry",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/9412 Class chemistry.pdf"
      },
      {
        "title": "Biology final",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/9312 Biology final.pdf"
      }
    ]
  },
  {
    "classId": 13,
    "className": "NURSERY",
    "items": [
      {
        "title": "III part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/13III part.pdf"
      },
      {
        "title": "II part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/12II part.pdf"
      },
      {
        "title": "I part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/11I part.pdf"
      },
      {
        "title": "Writing-01-37-72",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/10Writing-01-37-72.pdf"
      }
    ]
  },
  {
    "classId": 14,
    "className": "LKG",
    "items": [
      {
        "title": "II part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/16II part.pdf"
      },
      {
        "title": "I part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/15I part.pdf"
      },
      {
        "title": "Writing-01-37-72",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/14Writing-01-37-72.pdf"
      }
    ]
  },
  {
    "classId": 15,
    "className": "UKG",
    "items": [
      {
        "title": "III part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/19III part.pdf"
      },
      {
        "title": "II part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/18II part.pdf"
      },
      {
        "title": "I part",
        "url": "https://www.krishnapublicschoolmeerut.in/HWContent/17I part.pdf"
      }
    ]
  }
];
