/**
 * messages — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /directormessage.php, /principalmessage.php
 */
export interface LeadershipMessage {
  role: "director" | "principal";
  name: string | null;
  title: string;
  body: string;
  image: string | null;
}

export const messages: LeadershipMessage[] = [
  {
    role: "director",
    name: null, // TODO: get from school office
    title: "Director's Message",
    body: `KRISHNA PUBLIC SCHOOL is situated on Delhi Roorkee highway, near Jatoli (Shradhapuri), Byepass Road at Meerut. Its Building and lush green lawn instantly catch the eyes of the passerby. The institute is ideally located in a pollution free environment, surrounding with natural landscape dominated by trees and plant conducive to academic environment. The present building is beautifully designed having Administration block, lecture rooms, Digi classes,Library, Computer Center, Dance and Music room,Fine art room, Laboratories (Physics,Chemistry,Biology,Mathematics,Geography Labs) etc.`,
    image: null,
  },
  {
    role: "principal",
    name: null, // TODO: get from school office
    title: "Principal's Message",
    body: `At, Krishna, we don\`t rest simply on attractive student-teacher ratios and curriculum requirements. We have always been clear that we are here to develop an innovative institution that stands for excellence in boy\`s education and provides a platform of lifetime opportunities for leadership. KPS is a place where every curricula and programmatic decision is based on a thoughtful and iterative approach to how students learn, develop, and thrive. We are rooted in a highly academic and intellectual approach, drawing in a large network of our unique academic and professional networks to contribute to our community. Our endeavor is to be prepared to give more thrust & attention to inculcate in the students a scientific temperament by promoting the spirit of enquiry, following a rational and objective approach. Our school is adequately equipped with facilities matching the most modern institutions, where we ensure that our words inculcate good moral and social values, regard for goodness, fairness, justice, truth, compassion, code of ethics for life, for work, profession and everyday dealings with others. We are committed to produce successful, responsible and proud citizens of tomorrow. We look forward to your active interest and co-operation for out combined efforts in bringing the best out of our students.`,
    image: `https://www.krishnapublicschoolmeerut.in/MessageImages/Principalmessage.jpg`,
  },
];
