/**
 * notices — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: homepage marquee — scraper found no items
 */
export interface Notice {
  id: string;
  title: string;
  date: string; // ISO date
  url?: string | null;
}

// TODO: replace with fetch('${API_BASE}/notices') when backend is ready
export const notices: Notice[] = [];
