/**
 * school-info — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: /schoolinfo.php — legacy page has no real body
 */
/**
 * Legacy /schoolinfo.php did not render any disclosure content. Phase 2 will
 * author the CBSE Mandatory Public Disclosure block. We retain whatever the
 * scraper found for reference.
 */
export interface SchoolInfoRaw {
  lists: string[][];
  paragraphs: string[];
}

export const schoolInfoRaw: SchoolInfoRaw = {
  "lists": [
    [
      "NH-58, By Pass, Shradha Puri, Kanker Khera ,Meerut",
      "krishna.pub.sch@gmail.com",
      "0121-2554335",
      "9219684588,"
    ],
    [
      "Photo Gallery",
      "School Calendar",
      "Downloads",
      "Contact us"
    ]
  ],
  "paragraphs": []
};
