/**
 * slider — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * Source: homepage hero carousel (/HeaderImages/*)
 */
export interface SliderImage {
  src: string;
  alt: string | null;
}

export const slider: SliderImage[] = [
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/1754520948_1246715725488327_470967662499856384_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/1854521125_1246715768821656_6457391168127762432_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/1954432698_1246716302154936_5328040864948158464_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2054523833_1246716118821621_708533354592468992_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2154727289_1246716032154963_8182662956652167168_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2254727512_1246715965488303_6565115261513367552_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2354728527_1246716338821599_5365474627374022656_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2454729283_1246716528821580_6888996417432453120_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2554798708_1246716552154911_8851581882253443072_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2655439728_1246716375488262_6230259802728038400_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2755451603_1246715682154998_3889866285583958016_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2855455406_1246715875488312_6520226711466934272_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/2955462364_1246716662154900_6447491131071528960_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/3055483216_1246716438821589_631797896924102656_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/3155514037_1246715605488339_7524703305826566144_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/3255539994_1246716012154965_7374756252242411520_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/3355554574_1246715825488317_3328434646051454976_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/3455680115_1246715642155002_9008844901525225472_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/3555680258_1246716095488290_4113088410405568512_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/3656140458_1246715895488310_3609833889603780608_n.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/38print_6@12x-100.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/39print_6@12x-100.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/40print_7@12x-100.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/HeaderImages/41print_8@12x-100.jpg",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/./img/home/slider/prev.png",
    "alt": null
  },
  {
    "src": "https://www.krishnapublicschoolmeerut.in/./img/home/slider/next.png",
    "alt": null
  }
];
