/**
 * Transforms scripts/output/raw-scraped.json + mappings.json into typed
 * TypeScript content modules under src/content/scraped/.
 *
 * Also produces scripts/output/SCRAPE_REPORT.md describing what was captured
 * and what remains as gaps to enrich in Phase 2.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = resolve(__dirname, "output");
const RAW_PATH = resolve(OUTPUT_DIR, "raw-scraped.json");
const MAP_PATH = resolve(OUTPUT_DIR, "mappings.json");
const CONTENT_DIR = resolve(__dirname, "..", "src", "content", "scraped");
const REPORT_PATH = resolve(OUTPUT_DIR, "SCRAPE_REPORT.md");

interface ScrapedPage {
  kind: string;
  slug: string;
  url: string;
  query?: Record<string, string | number>;
  status: number;
  ok: boolean;
  title: string | null;
  metaDescription: string | null;
  headings: { level: string; text: string }[];
  paragraphs: string[];
  lists: string[][];
  tables: { headers: string[]; rows: string[][] }[];
  images: { src: string; alt: string | null }[];
  downloads: { href: string; text: string }[];
  rawLength: number;
  error?: string;
}
interface RawOutput {
  scrapedAt: string;
  base: string;
  pages: ScrapedPage[];
  sliderImages: { src: string; alt: string | null }[];
  noticeBoard: { text: string; href: string | null }[];
  errors: { url: string; message: string }[];
}
interface Mappings {
  galleryCategories: { id: number; name: string }[];
  homeworkClasses: { id: number; name: string }[];
}

// Patterns that identify chrome leakage in paragraphs/headings
const CHROME_PATTERNS = [
  /^Study Material Verify TC$/i,
  /^Follow us -?$/i,
  /^Copyright © \d{4}/i,
  /^Design & Developed By/i,
  /^Name \* Email \* Mobile\* Message \*/i,
  /^(View Gallery|View Home Work|Downloads)$/i,
  /^(Notice Board|We'?re Social|Contact Info|Usefull Links|Photo Gallery|School Calendar|Contact us)$/i,
  /^(NH-\d|krishna\.pub\.sch@gmail|0121-\d|9219684588)/i,
];

const CHROME_IMG_PATTERNS = [
  /simple-php-captcha/i,
  /\/images\/logo\.png/i,
  /\/images\/no\.jpg/i,
  /\/images\/about-img/i,
];

function isChromeParagraph(p: string): boolean {
  if (p.length < 3) return true;
  return CHROME_PATTERNS.some((re) => re.test(p));
}
function isChromeImage(src: string): boolean {
  return CHROME_IMG_PATTERNS.some((re) => re.test(src));
}
function cleanParagraphs(paras: string[]): string[] {
  return paras
    .map((p) => p.trim())
    .filter((p) => p && !isChromeParagraph(p))
    .filter((p, i, a) => a.indexOf(p) === i);
}
function cleanImages(
  imgs: { src: string; alt: string | null }[],
): { src: string; alt: string | null }[] {
  return imgs.filter((i) => !isChromeImage(i.src));
}
function cleanHeadings(hs: { level: string; text: string }[]): string[] {
  return hs
    .map((h) => h.text.trim())
    .filter(
      (t) =>
        t &&
        !/^(Notice Board|We'?re Social|Contact Info|Usefull Links|Phone|Email|Address)$/i.test(
          t,
        ),
    )
    .filter((t, i, a) => a.indexOf(t) === i);
}
function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
function escapeBackticks(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function tsHeader(moduleName: string, sourceNote: string): string {
  return `/**
 * ${moduleName} — auto-generated by scripts/transform-scraped.ts from the
 * legacy site scrape. Do not edit by hand; regenerate with:
 *   pnpm run transform
 *
 * ${sourceNote}
 */
`;
}

function writeString(name: string, value: string): string {
  return "`" + escapeBackticks(value) + "`";
}

// ----- main ----------------------------------------------------------------

async function main() {
  const raw: RawOutput = JSON.parse(await readFile(RAW_PATH, "utf-8"));
  const maps: Mappings = JSON.parse(await readFile(MAP_PATH, "utf-8"));
  await mkdir(CONTENT_DIR, { recursive: true });

  const page = (slug: string): ScrapedPage | undefined =>
    raw.pages.find((p) => p.slug === slug);

  const gaps: string[] = [];

  // -------- messages.ts --------
  const director = page("directormessage");
  const principal = page("principalmessage");
  const directorText = director ? cleanParagraphs(director.paragraphs)[0] ?? "" : "";
  const principalText = principal ? cleanParagraphs(principal.paragraphs)[0] ?? "" : "";
  const directorImg =
    director?.images.filter(
      (i) => !isChromeImage(i.src) && /MessageImages/i.test(i.src),
    )[0]?.src ?? null;
  const principalImg =
    principal?.images.filter(
      (i) => !isChromeImage(i.src) && /MessageImages/i.test(i.src),
    )[0]?.src ?? null;
  if (!directorText) gaps.push("director message body is empty");
  if (!principalText) gaps.push("principal message body is empty");
  if (!directorImg) gaps.push("director portrait image not found");

  await writeFile(
    resolve(CONTENT_DIR, "messages.ts"),
    tsHeader(
      "messages",
      "Source: /directormessage.php, /principalmessage.php",
    ) +
      `export interface LeadershipMessage {
  role: "director" | "principal";
  name: string | null;
  title: string;
  body: string;
  image: string | null;
}

export const messages: LeadershipMessage[] = [
  {
    role: "director",
    name: null, // TODO: get from school office
    title: "Director's Message",
    body: ${writeString("director", directorText)},
    image: ${directorImg ? writeString("img", directorImg) : "null"},
  },
  {
    role: "principal",
    name: null, // TODO: get from school office
    title: "Principal's Message",
    body: ${writeString("principal", principalText)},
    image: ${principalImg ? writeString("img", principalImg) : "null"},
  },
];
`,
    "utf-8",
  );

  // -------- about.ts --------
  const about = page("aboutus");
  const mission = page("mission");
  const vision = page("visionmission");
  const moto = page("schoolmoto");
  const song = page("schoolsong");

  const aboutBody = about ? cleanParagraphs(about.paragraphs)[0] ?? "" : "";
  const missionBody = mission ? cleanParagraphs(mission.paragraphs).join("\n\n") : "";
  const visionBody = vision ? cleanParagraphs(vision.paragraphs).join("\n\n") : "";
  const motoBody = moto ? cleanParagraphs(moto.paragraphs).join("\n\n") : "";
  const songBody = song ? cleanParagraphs(song.paragraphs).join("\n\n") : "";
  if (!aboutBody) gaps.push("about body is empty");

  await writeFile(
    resolve(CONTENT_DIR, "about.ts"),
    tsHeader(
      "about",
      "Source: /aboutus.php, /mission.php, /visionmission.php, /schoolmoto.php, /schoolsong.php",
    ) +
      `export interface AboutContent {
  about: string;
  mission: string;
  vision: string;
  moto: string;
  song: string;
}

export const about: AboutContent = {
  about: ${writeString("about", aboutBody)},
  mission: ${writeString("mission", missionBody)},
  vision: ${writeString("vision", visionBody)},
  moto: ${writeString("moto", motoBody)},
  song: ${writeString("song", songBody)},
};
`,
    "utf-8",
  );

  // -------- facilities.ts --------
  const facilities: {
    id: number;
    slug: string;
    name: string;
    description: string;
    images: string[];
  }[] = [];
  for (let i = 1; i <= 13; i++) {
    const p = page(`infrastructure-${i}`);
    if (!p) continue;
    const heading = cleanHeadings(p.headings)[0];
    if (!heading) {
      gaps.push(`infrastructure InfraId=${i} has no heading — empty record`);
      continue;
    }
    const desc = cleanParagraphs(p.paragraphs).join("\n\n");
    const imgs = cleanImages(p.images)
      .filter((img) => /InfraImages/i.test(img.src))
      .map((img) => img.src);
    if (!imgs.length)
      gaps.push(`infrastructure InfraId=${i} "${heading}" has no images`);
    if (!desc)
      gaps.push(`infrastructure InfraId=${i} "${heading}" has no description`);
    facilities.push({
      id: i,
      slug: slugify(heading),
      name: heading,
      description: desc,
      images: imgs,
    });
  }
  await writeFile(
    resolve(CONTENT_DIR, "facilities.ts"),
    tsHeader("facilities", "Source: /infrastructure.php?InfraId=1..13") +
      `export interface Facility {
  id: number;
  slug: string;
  name: string;
  description: string;
  images: string[];
}

export const facilities: Facility[] = ${JSON.stringify(facilities, null, 2)};
`,
    "utf-8",
  );

  // -------- gallery.ts --------
  const galleryNameById = new Map(maps.galleryCategories.map((g) => [g.id, g.name]));
  const gallery: {
    categoryId: number;
    slug: string;
    name: string;
    images: { url: string; caption: string | null }[];
  }[] = [];
  for (let i = 1; i <= 15; i++) {
    const p = page(`gallery-${i}`);
    if (!p) continue;
    const name = galleryNameById.get(i) ?? `Archive Gallery ${i}`;
    const imgs = cleanImages(p.images)
      .filter((img) => /IGTImages/i.test(img.src))
      .map((img) => ({ url: img.src, caption: img.alt }));
    if (!galleryNameById.has(i) && imgs.length === 0) continue;
    if (!galleryNameById.has(i))
      gaps.push(
        `gallery GalleryCatId=${i} has ${imgs.length} images but no title — flagged as archive`,
      );
    gallery.push({
      categoryId: i,
      slug: slugify(name),
      name,
      images: imgs,
    });
  }
  await writeFile(
    resolve(CONTENT_DIR, "gallery.ts"),
    tsHeader("gallery", "Source: /photogallery.php, /gallery.php?GalleryCatId=1..15") +
      `export interface GalleryImage {
  url: string;
  caption: string | null;
}

export interface GalleryCategory {
  categoryId: number;
  slug: string;
  name: string;
  images: GalleryImage[];
}

export const gallery: GalleryCategory[] = ${JSON.stringify(gallery, null, 2)};
`,
    "utf-8",
  );

  // -------- downloads.ts --------
  const dlPage = page("downloads");
  const downloads =
    dlPage?.downloads.map((d) => ({
      title: d.href.split("/").pop()?.replace(/^\d+/, "").replace(/\.pdf$/i, "").trim() ||
        d.text,
      url: d.href,
    })) ?? [];
  if (!downloads.length) gaps.push("downloads page yielded no files");
  await writeFile(
    resolve(CONTENT_DIR, "downloads.ts"),
    tsHeader("downloads", "Source: /downloads.php") +
      `export interface DownloadItem {
  title: string;
  url: string;
}

export const downloads: DownloadItem[] = ${JSON.stringify(downloads, null, 2)};
`,
    "utf-8",
  );

  // -------- notices.ts --------
  // The scraper didn't capture marquee notices (heuristic mismatch). Emit empty
  // with a TODO so Phase 2 can populate or we plug a real feed later.
  if (!raw.noticeBoard.length) gaps.push("notice board: no entries captured by scraper — will need manual seed");
  await writeFile(
    resolve(CONTENT_DIR, "notices.ts"),
    tsHeader("notices", "Source: homepage marquee — scraper found no items") +
      `export interface Notice {
  id: string;
  title: string;
  date: string; // ISO date
  url?: string | null;
}

// TODO: replace with fetch('\${API_BASE}/notices') when backend is ready
export const notices: Notice[] = ${JSON.stringify(
        raw.noticeBoard.map((n, i) => ({
          id: `legacy-${i + 1}`,
          title: n.text,
          date: raw.scrapedAt.slice(0, 10),
          url: n.href,
        })),
        null,
        2,
      )};
`,
    "utf-8",
  );

  // -------- school-info.ts --------
  const si = page("schoolinfo");
  const siLists = si?.lists ?? [];
  await writeFile(
    resolve(CONTENT_DIR, "school-info.ts"),
    tsHeader("school-info", "Source: /schoolinfo.php — legacy page has no real body") +
      `/**
 * Legacy /schoolinfo.php did not render any disclosure content. Phase 2 will
 * author the CBSE Mandatory Public Disclosure block. We retain whatever the
 * scraper found for reference.
 */
export interface SchoolInfoRaw {
  lists: string[][];
  paragraphs: string[];
}

export const schoolInfoRaw: SchoolInfoRaw = ${JSON.stringify(
      { lists: siLists, paragraphs: cleanParagraphs(si?.paragraphs ?? []) },
      null,
      2,
    )};
`,
    "utf-8",
  );
  gaps.push(
    "school-info: legacy page has no disclosure body — needs full Phase 2 authoring",
  );

  // -------- contact.ts --------
  const contact = page("contactus");
  const addressLine =
    contact?.paragraphs.find((p) => /Shradha\s*Puri|Kanker\s*Khera|NH-?58/i.test(p)) ??
    "NH-58, By Pass, Shradha Puri, Kanker Khera, Meerut";
  const phones = ["0121-2554335", "9219684588"];
  const email = "krishna.pub.sch@gmail.com";
  await writeFile(
    resolve(CONTENT_DIR, "contact.ts"),
    tsHeader("contact", "Source: /contactus.php") +
      `export interface ContactInfo {
  address: string;
  phones: string[];
  emails: string[];
  socials: { platform: string; url: string }[];
}

export const contact: ContactInfo = {
  address: ${writeString("addr", addressLine)},
  phones: ${JSON.stringify(phones)},
  emails: ${JSON.stringify([email])},
  socials: [], // TBD — legacy site had no live social links
};
`,
    "utf-8",
  );

  // -------- homework.ts --------
  const hwByClass = maps.homeworkClasses.map((cls) => {
    const p = page(`homework-${cls.id}`);
    const items =
      p?.downloads.map((d) => {
        const filename = d.href.split("/").pop() ?? "";
        const pretty = filename
          .replace(/^\d+/, "")
          .replace(/\.pdf$/i, "")
          .replace(/_+/g, " ")
          .trim();
        return { title: pretty || filename, url: d.href };
      }) ?? [];
    if (!items.length) gaps.push(`homework DCatId=${cls.id} ${cls.name}: no PDFs`);
    return { classId: cls.id, className: cls.name, items };
  });
  await writeFile(
    resolve(CONTENT_DIR, "homework.ts"),
    tsHeader("homework", "Source: /hwclass.php, /homeworklist.php?DCatId=1..15") +
      `export interface HomeworkItem {
  title: string;
  url: string;
}

export interface HomeworkClass {
  classId: number;
  className: string;
  items: HomeworkItem[];
}

export const homework: HomeworkClass[] = ${JSON.stringify(hwByClass, null, 2)};
`,
    "utf-8",
  );

  // -------- slider.ts --------
  await writeFile(
    resolve(CONTENT_DIR, "slider.ts"),
    tsHeader("slider", "Source: homepage hero carousel (/HeaderImages/*)") +
      `export interface SliderImage {
  src: string;
  alt: string | null;
}

export const slider: SliderImage[] = ${JSON.stringify(raw.sliderImages, null, 2)};
`,
    "utf-8",
  );

  // -------- SCRAPE_REPORT.md --------
  const ok = raw.pages.filter((p) => p.ok).length;
  const failed = raw.pages.filter((p) => !p.ok).length;
  const totalImgs = raw.pages.reduce((a, p) => a + cleanImages(p.images).length, 0);
  const totalDls = raw.pages.reduce((a, p) => a + p.downloads.length, 0);

  const report = `# Scrape Report — Krishna Public School (legacy)

- Source: ${raw.base}
- Scraped at: ${raw.scrapedAt}
- Pages attempted: ${raw.pages.length}
- Pages OK: ${ok}
- Pages failed: ${failed}
- Content images (captcha/logo excluded): ${totalImgs}
- Download files (PDF/DOC/etc.): ${totalDls}
- Homepage slider images: ${raw.sliderImages.length}
- Notice board items: ${raw.noticeBoard.length}

## Pages by kind

${Object.entries(
  raw.pages.reduce<Record<string, number>>((a, p) => {
    a[p.kind] = (a[p.kind] ?? 0) + 1;
    return a;
  }, {}),
)
  .map(([k, v]) => `- ${k}: ${v}`)
  .join("\n")}

## Gallery categories captured

${maps.galleryCategories.map((g) => `- ${g.id}: ${g.name}`).join("\n")}

Unnamed gallery IDs: 7, 8, 10, 13, 14, 15 (some contain images — flagged as "Archive Gallery N").

## Homework categories captured

${maps.homeworkClasses.map((c) => `- ${c.id}: ${c.name}`).join("\n")}

## Content gaps — Phase 2 should address these

${gaps.map((g) => `- ${g}`).join("\n") || "- (none)"}

## Legacy chrome observations

The legacy layout repeats "Notice Board", "We're Social", "Contact Info",
"Usefull Links" and a "Study Material Verify TC" nav on every page; the
transform strips these. The PHP captcha (\`simple-php-captcha.php\`) leaks as an
image on every page — also stripped. Copyright reads "© 2017", i.e. the site
has not had a content refresh in 8 years.

## Files emitted

- src/content/scraped/messages.ts
- src/content/scraped/about.ts
- src/content/scraped/facilities.ts
- src/content/scraped/gallery.ts
- src/content/scraped/downloads.ts
- src/content/scraped/notices.ts
- src/content/scraped/school-info.ts
- src/content/scraped/contact.ts
- src/content/scraped/homework.ts
- src/content/scraped/slider.ts

## Errors during fetch

${raw.errors.length ? raw.errors.map((e) => `- ${e.url}: ${e.message}`).join("\n") : "- (none)"}

## What's next

See the project [README](../../README.md) for quickstart, and
[docs/PROGRESS.md](../../docs/PROGRESS.md) for the log of what each phase
produced.
`;

  await writeFile(REPORT_PATH, report, "utf-8");
  console.log(`Wrote SCRAPE_REPORT.md and 10 content files to ${CONTENT_DIR}`);
  console.log(
    `OK=${ok} failed=${failed} images=${totalImgs} downloads=${totalDls} slider=${raw.sliderImages.length} gaps=${gaps.length}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
